version: 2
jobs:
    one:
 	docker:
	     - image: cimg/ruby:2.6.8

	steps:
	    - checkout
	    - run: sleep 25
    two:
	docker:
	     - image: cimg/ruby:3.0.2

	steps:
	    - checkout
	    - run: echo "A more familiar hi"
	    - run: sleep

workflows:
     version: 2
     one_and_two:
	jobs:
